"""
LangGraph workflows for 5-Why, fishbone, and CAPA/8D drafts (plan.md §5).
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any, TypedDict

from langgraph.graph import END, StateGraph
from openai import AsyncOpenAI

from app.config import settings
from app.services.component_alias import alias_sql_hint
from app.services.rag_service import RAGService
from app.services.sql_service import TextToSQLService
from app.utils import QueryValidator

logger = logging.getLogger("rag_app.quality_langgraph")


def _safe_json_loads(content: str) -> dict[str, Any]:
    """Parse LLM JSON output, degrading to an empty dict on malformed responses.

    Even with response_format=json_object the API can return malformed or
    truncated JSON; an unhandled JSONDecodeError would surface as a 500 with a
    traceback leaked to the caller.
    """
    try:
        return json.loads(content)
    except (json.JSONDecodeError, TypeError) as e:
        logger.warning("LLM returned invalid JSON: %s | content: %s", e, content[:200])
        return {}


_workflows_singleton: QualityLangGraphWorkflows | None = None


def init_quality_workflows(
    rag_service: RAGService | None, sql_service: TextToSQLService | None
) -> None:
    global _workflows_singleton
    _workflows_singleton = None
    if not settings.OPENAI_API_KEY:
        return
    try:
        _workflows_singleton = QualityLangGraphWorkflows(rag_service, sql_service)
        logger.info("Quality LangGraph workflows initialized")
    except Exception as e:
        logger.warning("Quality workflows not initialized: %s", type(e).__name__)


def get_quality_workflows() -> QualityLangGraphWorkflows:
    if _workflows_singleton is None:
        raise RuntimeError("Quality workflows unavailable")
    return _workflows_singleton


class FiveWhyState(TypedDict, total=False):
    problem_statement: str
    component: str | None
    anomaly_label: str | None
    rag_context: str
    sql_context: str
    output: dict[str, Any]


class FishboneState(TypedDict, total=False):
    effect: str
    station: str
    rag_context: str
    sql_context: str
    output: dict[str, Any]


class DraftState(TypedDict, total=False):
    mode: str
    problem_statement: str
    part_number: str | None
    component: str | None
    rag_context: str
    sql_context: str
    output: dict[str, Any]


class QualityLangGraphWorkflows:
    """LangGraph pipelines: retrieve context then return structured JSON."""

    def __init__(
        self,
        rag_service: RAGService | None,
        sql_service: TextToSQLService | None,
    ) -> None:
        self.rag_service = rag_service
        self.sql_service = sql_service
        if not settings.OPENAI_API_KEY:
            raise ValueError("OPENAI_API_KEY is required for quality agents")
        self.client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY, timeout=25.0, max_retries=2)
        self.model = settings.AGENT_MODEL

        # Pre-compile graphs once at startup — avoids expensive recompilation per request
        self._five_why_graph = self._build_five_why_graph()
        self._fishbone_graph = self._build_fishbone_graph()
        self._draft_graph = self._build_draft_graph()
        logger.info("Quality LangGraph graphs pre-compiled (model=%s)", self.model)

    async def _retrieve_rag(self, query: str, top_k: int = 6) -> str:
        if not self.rag_service:
            return ""
        try:
            res = await self.rag_service.get_similar_chunks(question=query, top_k=top_k)
            chunks = res.get("chunks") or []
            parts = []
            for i, ch in enumerate(chunks, 1):
                text = ch.get("text", "")[:1200]
                fn = ch.get("metadata", {}).get("filename", "unknown")
                parts.append(f"[{i}] {fn}: {text}")
            return "\n".join(parts)
        except Exception as e:
            logger.warning("RAG retrieval failed for quality workflow: %s", type(e).__name__)
            return ""

    async def _retrieve_sql_snippet(self, question: str) -> str:
        if not self.sql_service:
            return ""
        try:
            gen = await self.sql_service.generate_sql_for_approval(question)
            sql = gen.get("sql", "")

            # Guard against dangerous SQL generated by the LLM
            if QueryValidator.check_dangerous_sql(sql):
                logger.warning("Workflow SQL blocked (dangerous pattern): %s", sql[:80])
                return ""

            exec_res = await self.sql_service.execute_approved_query(gen["query_id"], approved=True)
            if exec_res.get("status") != "executed":
                return ""
            rows = exec_res.get("results") or []
            return json.dumps(rows[:30], default=str)
        except Exception as e:
            logger.warning("SQL auto-run failed for quality workflow: %s", type(e).__name__)
            return ""

    # ── 5-Why nodes ────────────────────────────────────────────────────────────

    async def _node_five_why_gather(self, state: FiveWhyState) -> FiveWhyState:
        problem = state["problem_statement"]
        component = state.get("component") or ""
        # component (from CLaimLens handoff / extraction) scopes PFMEA / NCR evidence.
        rag_q = f"{problem} {component}".strip()
        sql_hint = alias_sql_hint(component)
        rag_context, sql_context = await asyncio.gather(
            self._retrieve_rag(rag_q, top_k=6),
            self._retrieve_sql_snippet(
                f"Recent defects and failure modes for component {component or 'N/A'} "
                f"related to: {problem}. Limit 20 rows."
                + (f" {sql_hint}" if sql_hint else "")
            ),
        )
        return {**state, "rag_context": rag_context, "sql_context": sql_context}

    async def _node_five_why_synthesize(self, state: FiveWhyState) -> FiveWhyState:
        system = (
            "You are a senior manufacturing quality engineer. "
            "Return ONLY valid JSON matching this shape: "
            '{"problem_statement": str, "whys": [{"level": int, "why": str, "evidence_source": str}], '
            '"root_cause": str, "recommended_action": str, "confidence_score": number 0.0-1.0}. '
            "Use 3 to 5 whys. Ground each why in rag_context or sql_context when possible. "
            "confidence_score must be between 0.0 and 1.0."
        )
        user = json.dumps(
            {
                "problem_statement": state.get("problem_statement", ""),
                "component": state.get("component"),
                "anomaly_label": state.get("anomaly_label"),
                "rag_context": state.get("rag_context", ""),
                "sql_context": state.get("sql_context", ""),
            }
        )
        resp = await self.client.chat.completions.create(
            model=self.model,
            temperature=0.2,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        )
        content = resp.choices[0].message.content or "{}"
        output = _safe_json_loads(content)

        # Clamp confidence_score to [0, 1] in case LLM returns out-of-range value
        if "confidence_score" in output:
            output["confidence_score"] = max(0.0, min(1.0, float(output["confidence_score"])))

        return {**state, "output": output}

    def _build_five_why_graph(self):
        graph = StateGraph(FiveWhyState)
        graph.add_node("gather", self._node_five_why_gather)
        graph.add_node("synthesize", self._node_five_why_synthesize)
        graph.set_entry_point("gather")
        graph.add_edge("gather", "synthesize")
        graph.add_edge("synthesize", END)
        return graph.compile()

    async def run_five_why(
        self,
        problem_statement: str,
        component: str | None = None,
        anomaly_label: str | None = None,
    ) -> dict[str, Any]:
        final_state = await self._five_why_graph.ainvoke(
            {
                "problem_statement": problem_statement,
                "component": component,
                "anomaly_label": anomaly_label,
            }
        )
        return final_state.get("output") or {}

    # ── Fishbone nodes ─────────────────────────────────────────────────────────

    async def _node_fishbone_gather(self, state: FishboneState) -> FishboneState:
        effect = state["effect"]
        station = state.get("station", "")
        rag_q = f"{effect} {station} PFMEA control plan work instruction causes"
        rag_context, sql_context = await asyncio.gather(
            self._retrieve_rag(rag_q, top_k=6),
            self._retrieve_sql_snippet(
                f"Top failure modes at {station} if relevant for: {effect}. Group by failure_mode, last 180 days."
            ),
        )
        return {**state, "rag_context": rag_context, "sql_context": sql_context}

    async def _node_fishbone_synthesize(self, state: FishboneState) -> FishboneState:
        system = (
            "You are a manufacturing QE building an Ishikawa (6M) fishbone. "
            "Return ONLY JSON: "
            '{"effect": str, "bones": {"Man": [...], "Machine": [...], "Method": [...], '
            '"Material": [...], "Measurement": [...], "Environment": [...]}} '
            'Each bone entry: {"cause": str, "evidence": str, "weight": number 0.0-1.0}. '
            "All weight values must be between 0.0 and 1.0."
        )
        user = json.dumps(
            {
                "effect": state.get("effect", ""),
                "station": state.get("station", ""),
                "rag_context": state.get("rag_context", ""),
                "sql_context": state.get("sql_context", ""),
            }
        )
        resp = await self.client.chat.completions.create(
            model=self.model,
            temperature=0.2,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        )
        content = resp.choices[0].message.content or "{}"
        output = _safe_json_loads(content)

        # Clamp bone weights to [0, 1]
        for bone_list in output.get("bones", {}).values():
            for entry in bone_list:
                if "weight" in entry:
                    entry["weight"] = max(0.0, min(1.0, float(entry["weight"])))

        return {**state, "output": output}

    def _build_fishbone_graph(self):
        graph = StateGraph(FishboneState)
        graph.add_node("gather", self._node_fishbone_gather)
        graph.add_node("synthesize", self._node_fishbone_synthesize)
        graph.set_entry_point("gather")
        graph.add_edge("gather", "synthesize")
        graph.add_edge("synthesize", END)
        return graph.compile()

    async def run_fishbone(self, effect: str, station: str | None = None) -> dict[str, Any]:
        final_state = await self._fishbone_graph.ainvoke(
            {"effect": effect, "station": station or ""}
        )
        return final_state.get("output") or {}

    # ── CAPA / 8D draft nodes ──────────────────────────────────────────────────

    async def _node_draft_gather(self, state: DraftState) -> DraftState:
        problem = state["problem_statement"]
        scope = state.get("component") or state.get("part_number") or ""
        # Prefer an explicit BOM part_number; else translate the descriptive component.
        sql_hint = "" if state.get("part_number") else alias_sql_hint(state.get("component"))
        rag_context, sql_context = await asyncio.gather(
            self._retrieve_rag(f"{problem} {scope} CAPA 8D PFMEA history", top_k=8),
            self._retrieve_sql_snippet(
                f"Recent defects, CAPAs, and 8Ds for {scope or 'N/A'} related to: {problem}"
                + (f" {sql_hint}" if sql_hint else "")
            ),
        )
        return {**state, "rag_context": rag_context, "sql_context": sql_context}

    async def _node_draft_synthesize(self, state: DraftState) -> DraftState:
        mode = state.get("mode", "capa")
        if mode == "8d":
            system = (
                "Return ONLY JSON for an 8D draft with keys: "
                "report_number (placeholder string), part_number, problem_statement, "
                "d1_team, d2_problem_desc, d3_containment, d4_root_cause, d5_perm_action, "
                "d6_implemented, d7_prevention, d8_closure. "
                "Use evidence from context; do not invent real person names."
            )
        else:
            system = (
                "Return ONLY JSON for a CAPA draft with keys: "
                "capa_number (placeholder), title, problem_statement, root_cause, "
                "corrective_action, preventive_action, owner (generic role), "
                "status (open), due_date (ISO ~30 days out). "
                "Ground content in provided context where possible."
            )
        user = json.dumps(
            {
                "mode": mode,
                "problem_statement": state.get("problem_statement", ""),
                "component": state.get("component"),
                "part_number": state.get("part_number"),
                "rag_context": state.get("rag_context", ""),
                "sql_context": state.get("sql_context", ""),
            }
        )
        resp = await self.client.chat.completions.create(
            model=self.model,
            temperature=0.2,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        )
        content = resp.choices[0].message.content or "{}"
        return {**state, "output": _safe_json_loads(content)}

    def _build_draft_graph(self):
        graph = StateGraph(DraftState)
        graph.add_node("gather", self._node_draft_gather)
        graph.add_node("synthesize", self._node_draft_synthesize)
        graph.set_entry_point("gather")
        graph.add_edge("gather", "synthesize")
        graph.add_edge("synthesize", END)
        return graph.compile()

    async def run_draft(
        self,
        mode: str,
        problem_statement: str,
        part_number: str | None = None,
        component: str | None = None,
    ) -> dict[str, Any]:
        final_state = await self._draft_graph.ainvoke(
            {
                "mode": mode,
                "problem_statement": problem_statement,
                "part_number": part_number,
                "component": component,
            }
        )
        return final_state.get("output") or {}
